services:
  postgres:
    image: postgres:17
    container_name: identity-service-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - identity-service-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailpit:
    image: axllent/mailpit:v1.30
    container_name: identity-service-mailpit

    ports:
      - "1025:1025"
      - "8025:8025"

    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: identity-service-app

    user: "${HOST_UID}:${HOST_GID}"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_BASE_URL: http://localhost:8080
      JWT_ISSUER: http://localhost:8080

    ports:
      - "8080:8080"

    volumes:
      - ./keys:/app/keys:ro

    depends_on:
      postgres:
        condition: service_healthy

      mailpit:
        condition: service_healthy

volumes:
  identity-service-postgres-data: