spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: mailpit
    port: 1025

logging:
  level:
    com.spsk1313.identityservice: INFO
  pattern:
    correlation: '%replace( [requestId=%X{requestId}] ){''\[requestId=\s*\]'', ''''}'

app:
  verification:
    base-url: ${APP_BASE_URL:http://localhost:8080}

  jwt:
    issuer: ${JWT_ISSUER:http://localhost:8080}
    access-token-ttl: 15m
    private-key: file:/app/keys/private.pem
    public-key: file:/app/keys/public.pem