spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025

logging:
  level:
    com.spsk1313.identityservice: DEBUG
  pattern:
    correlation: '%replace( [requestId=%X{requestId}] ){''\[requestId=\s*\]'', ''''}'

app:
  verification:
    base-url: http://localhost:8080